
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courseimooc?useSSL=false&serverTimezone=UTC
    username: courseimooc
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.ahut.server.mapper: trace