server:
  port: 9001
  servlet:
    context-path: /system
spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://localhost:3306/courseimooc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: courseimooc
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/